require 'pry'
require 'minitest/autorun'
require 'minitest/pride'
require 'csv'
require './lib/stat_tracker'
require './lib/team'
require './lib/game'
require './lib/game_team'
require 'simplecov'
SimpleCov.start
